//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://41.78.79.38:24000/filedownload.asmx")]
//[System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://localhost:16982/WebSite2/filedownload.asmx")]
public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback SendFileOperationCompleted;
    
    /// <remarks/>
    public Service() {
       // this.Url = "http://localhost:16982/WebSite2/filedownload.asmx";
        this.Url ="http://41.78.79.38:24000/filedownload.asmx";
    }
    
    /// <remarks/>
    public event SendFileCompletedEventHandler SendFileCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://41.78.79.38:24000/filedownload.asmx/SendFile", RequestNamespace = "http://41.78.79.38:24000/filedownload.asmx", ResponseNamespace = "http://41.78.79.38:24000/filedownload.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SendFile(string message, string nguva, string id) {
        object[] results = this.Invoke("SendFile", new object[] {
                    message,
                    nguva,
                    id});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendFile(string message, string nguva, string id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendFile", new object[] {
                    message,
                    nguva,
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSendFile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SendFileAsync(string message, string nguva, string id) {
        this.SendFileAsync(message, nguva, id, null);
    }
    
    /// <remarks/>
    public void SendFileAsync(string message, string nguva, string id, object userState) {
        if ((this.SendFileOperationCompleted == null)) {
            this.SendFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileOperationCompleted);
        }
        this.InvokeAsync("SendFile", new object[] {
                    message,
                    nguva,
                    id}, this.SendFileOperationCompleted, userState);
    }
    
    private void OnSendFileOperationCompleted(object arg) {
        if ((this.SendFileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendFileCompleted(this, new SendFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void SendFileCompletedEventHandler(object sender, SendFileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
