//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long Id { get; set; }
        public Nullable<long> msgId { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string avatar { get; set; }
        public string Notification { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string ReceiverId { get; set; }
        public string ReceiverName { get; set; }
        public string unread { get; set; }
        public string SenderId { get; set; }
        public string SenderName { get; set; }
        public string image { get; set; }
    }
}
