//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCredenitial
    {
        public string AccountNumber { get; set; }
        public string Pin { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Access { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<long> Atempts { get; set; }
        public string Connection { get; set; }
    }
}
