//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long ID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Opening { get; set; }
        public string LinkAccount { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public string image { get; set; }
        public string MappingCode { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string Currency { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string GiveDiscount { get; set; }
    }
}
