//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activeco
    {
        public long ID { get; set; }
        public string company { get; set; }
        public Nullable<decimal> dailyTarget { get; set; }
        public Nullable<decimal> monthlyTarget { get; set; }
        public Nullable<long> CompanyId { get; set; }
    }
}
