//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdSpace
    {
        public long Id { get; set; }
        public string SupplierId { get; set; }
        public string LocationName { get; set; }
        public string LocationUrl { get; set; }
        public string LocationSize { get; set; }
        public Nullable<int> TargetMinAge { get; set; }
        public string TargetSex { get; set; }
        public string Country { get; set; }
        public string AdLocator { get; set; }
        public string SpaceId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RevenueShare { get; set; }
        public string State { get; set; }
        public string TimeSlot { get; set; }
    }
}
