//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SupplierId { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> DailyMax { get; set; }
        public Nullable<decimal> DailyUsage { get; set; }
        public string Sex { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public string Location { get; set; }
        public string AdPosition { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ExpireryDate { get; set; }
        public string Status { get; set; }
        public string Placements { get; set; }
        public string City { get; set; }
        public Nullable<int> Radius { get; set; }
        public string Timeslots { get; set; }
        public Nullable<double> minLatitude { get; set; }
        public Nullable<double> maxLatitude { get; set; }
        public Nullable<double> minLongitude { get; set; }
        public Nullable<double> maxLongitude { get; set; }
    }
}
