//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUser
    {
        public long Id { get; set; }
        public string AccountNumber { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<long> TerminalId { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> Datelast { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Role { get; set; }
        public string SessionCode { get; set; }
    }
}
