//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCollection
    {
        public long Id { get; set; }
        public string Cashier { get; set; }
        public string CollectedBy { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Breakdown { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
    }
}
