//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long ID { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string location { get; set; }
        public string dated { get; set; }
    }
}
