//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public long Id { get; set; }
        public string Curency { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<bool> IsBase { get; set; }
        public string Company { get; set; }
    }
}
