//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyStat
    {
        public long Id { get; set; }
        public string ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Views { get; set; }
        public Nullable<long> Clicks { get; set; }
        public Nullable<long> comments { get; set; }
        public Nullable<long> Reservations { get; set; }
        public Nullable<long> Mobile { get; set; }
        public Nullable<long> PC { get; set; }
    }
}
