//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public long Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> SaburbId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Saburb { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string Status { get; set; }
        public string DeliveryType { get; set; }
        public string Receipt { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> DriverId { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string Invoice { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerNationalId { get; set; }
        public string Company { get; set; }
    }
}
