//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EqCode { get; set; }
        public string Make { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<decimal> Millage { get; set; }
        public Nullable<System.DateTime> AquisitionDate { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string Custodian { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string Status { get; set; }
        public string Thumbnail { get; set; }
        public string Image { get; set; }
    }
}
