//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public long Id { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Units { get; set; }
        public string Category { get; set; }
        public Nullable<long> FeatureCount { get; set; }
        public Nullable<long> EquipmentCount { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Area { get; set; }
    }
}
