//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public long ID { get; set; }
        public string AccountCode { get; set; }
        public string CustomerName { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Username { get; set; }
        public string Dated { get; set; }
        public Nullable<long> Period { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Wallet { get; set; }
        public Nullable<decimal> Purchases { get; set; }
        public Nullable<decimal> PurchasesToDate { get; set; }
        public string CompanyId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string IsParent { get; set; }
        public string Image { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<long> NetworkType { get; set; }
        public string City { get; set; }
        public string Suburb { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> Level1Count { get; set; }
        public Nullable<long> Level2Count { get; set; }
        public Nullable<long> Level3Count { get; set; }
        public Nullable<decimal> wallet2 { get; set; }
        public Nullable<decimal> wallet3 { get; set; }
        public Nullable<decimal> wallet1 { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string ConnectionId { get; set; }
    }
}
