//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long ID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> BuyingPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> Expected { get; set; }
        public Nullable<decimal> sold { get; set; }
        public Nullable<decimal> transfer { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> NewStock { get; set; }
        public Nullable<decimal> Returned { get; set; }
        public string company { get; set; }
        public string category { get; set; }
        public string SubCategory { get; set; }
        public Nullable<decimal> Swaps { get; set; }
        public Nullable<decimal> Reorder { get; set; }
        public string status { get; set; }
        public string ItemCode { get; set; }
        public string tax { get; set; }
        public string TopSeller { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Measure { get; set; }
        public string Image { get; set; }
        public string ThumbImage { get; set; }
        public string DicountType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Promotion { get; set; }
        public string Nation { get; set; }
        public string Manufacturer { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AdPosition { get; set; }
        public string PromoImage { get; set; }
        public string Featured { get; set; }
        public string ItemDescription { get; set; }
        public string ItmDescription { get; set; }
        public Nullable<bool> IsBulk { get; set; }
        public string Supplier { get; set; }
        public Nullable<bool> HasRecipe { get; set; }
        public Nullable<bool> NotForSale { get; set; }
        public Nullable<System.DateTime> AvailabilityDate { get; set; }
        public string AvailabilityInterval { get; set; }
        public string AvailabilityMatrix { get; set; }
    }
}
