//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public long Id { get; set; }
        public string ItemCode { get; set; }
        public string Image { get; set; }
        public string ImageThumb { get; set; }
        public string ImageType { get; set; }
        public string ImageDescription { get; set; }
        public string InageTitle { get; set; }
    }
}
