//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string accesslevel { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string prefix { get; set; }
        public string Location { get; set; }
        public Nullable<bool> PosUser { get; set; }
        public Nullable<bool> RetailUser { get; set; }
        public Nullable<bool> UsesBoth { get; set; }
        public Nullable<bool> Shifts { get; set; }
        public Nullable<bool> ManagerMenu { get; set; }
        public Nullable<bool> Tables { get; set; }
        public Nullable<bool> Payments { get; set; }
        public Nullable<bool> Reporting { get; set; }
        public Nullable<bool> Sales { get; set; }
        public Nullable<bool> Pricing { get; set; }
        public Nullable<bool> Barcoding { get; set; }
        public Nullable<bool> AddsProducts { get; set; }
        public Nullable<bool> Purchases { get; set; }
        public Nullable<bool> ManageUsers { get; set; }
        public Nullable<bool> ManagePos { get; set; }
        public Nullable<bool> Transfers { get; set; }
        public Nullable<bool> Accounts { get; set; }
        public Nullable<bool> OnShift { get; set; }
        public Nullable<bool> xreport { get; set; }
        public Nullable<bool> zreport { get; set; }
        public Nullable<bool> voidsale { get; set; }
        public string Email { get; set; }
        public string EmailPw { get; set; }
        public string AccountType { get; set; }
        public string Account { get; set; }
        public Nullable<bool> CashCollection { get; set; }
        public string ConnectionId { get; set; }
        public Nullable<bool> UsesDispatch { get; set; }
        public Nullable<System.DateTime> DateLastAccess { get; set; }
        public string Status { get; set; }
        public Nullable<bool> CreditNote { get; set; }
        public Nullable<bool> InventoryManagement { get; set; }
        public Nullable<bool> ManageStore { get; set; }
        public Nullable<bool> LossAuthorize { get; set; }
        public Nullable<bool> LossControl { get; set; }
        public Nullable<bool> MultiCompanyAccess { get; set; }
        public Nullable<bool> MCadmin { get; set; }
        public Nullable<bool> PosCustomers { get; set; }
        public Nullable<bool> GivesDiscounts { get; set; }
    }
}
