//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string Perpose { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<bool> FixedEmail { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public string Service { get; set; }
        public string ListName { get; set; }
        public string SmsSender { get; set; }
        public string SmsMessage { get; set; }
        public Nullable<bool> HasSms { get; set; }
    }
}
