//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingService
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string ListiningFolder { get; set; }
        public string Status { get; set; }
        public string Company { get; set; }
        public string StartMode { get; set; }
        public string FileFilter { get; set; }
        public string SendFileAs { get; set; }
        public string HasMailingList { get; set; }
        public string Description { get; set; }
        public string EmailSeparator { get; set; }
        public Nullable<int> StartPossition { get; set; }
        public Nullable<bool> HasSms { get; set; }
        public Nullable<int> SmsPosition { get; set; }
        public string SendingDetails { get; set; }
        public Nullable<int> EmailMessagePosition { get; set; }
        public Nullable<int> SmsMessagePosition { get; set; }
        public Nullable<bool> HasTemplate { get; set; }
        public Nullable<bool> HasEmail { get; set; }
    }
}
