//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailGroup
    {
        public long Id { get; set; }
        public string Receiver { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string CustomerId { get; set; }
    }
}
