//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public long Id { get; set; }
        public Nullable<long> MenuId { get; set; }
        public string Title { get; set; }
        public string LinkUrl { get; set; }
        public string CssClass { get; set; }
        public string HasSubMenu { get; set; }
        public string LinkType { get; set; }
        public string Section { get; set; }
    }
}
