//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyStat
    {
        public long Id { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<long> JanV { get; set; }
        public Nullable<long> JanC { get; set; }
        public Nullable<long> JanR { get; set; }
        public Nullable<long> JanE { get; set; }
        public Nullable<long> FebV { get; set; }
        public Nullable<long> FebC { get; set; }
        public Nullable<long> FebR { get; set; }
        public Nullable<long> FebE { get; set; }
        public Nullable<long> MarV { get; set; }
        public Nullable<long> MarC { get; set; }
        public Nullable<long> MarR { get; set; }
        public Nullable<long> MarE { get; set; }
        public Nullable<long> AprV { get; set; }
        public Nullable<long> AprC { get; set; }
        public Nullable<long> AprR { get; set; }
        public Nullable<long> AprE { get; set; }
        public Nullable<long> MayV { get; set; }
        public Nullable<long> MayC { get; set; }
        public Nullable<long> MayR { get; set; }
        public Nullable<long> MayE { get; set; }
        public Nullable<long> JunV { get; set; }
        public Nullable<long> JunC { get; set; }
        public Nullable<long> JunR { get; set; }
        public Nullable<long> JunE { get; set; }
        public Nullable<long> JulV { get; set; }
        public Nullable<long> JulC { get; set; }
        public Nullable<long> JulR { get; set; }
        public Nullable<long> JulE { get; set; }
        public Nullable<long> AugV { get; set; }
        public Nullable<long> AugC { get; set; }
        public Nullable<long> AugR { get; set; }
        public Nullable<long> AugE { get; set; }
        public Nullable<long> SepV { get; set; }
        public Nullable<long> SepC { get; set; }
        public Nullable<long> SepR { get; set; }
        public Nullable<long> SepE { get; set; }
        public Nullable<long> OctV { get; set; }
        public Nullable<long> OctC { get; set; }
        public Nullable<long> OctR { get; set; }
        public Nullable<long> OctE { get; set; }
        public Nullable<long> NovV { get; set; }
        public Nullable<long> NovC { get; set; }
        public Nullable<long> NovR { get; set; }
        public Nullable<long> NovE { get; set; }
        public Nullable<long> DecV { get; set; }
        public Nullable<long> DecC { get; set; }
        public Nullable<long> DecR { get; set; }
        public Nullable<long> DecE { get; set; }
    }
}
