//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkSale
    {
        public string Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Jan0 { get; set; }
        public Nullable<decimal> Jan1 { get; set; }
        public Nullable<decimal> Jan2 { get; set; }
        public Nullable<decimal> Jan3 { get; set; }
        public Nullable<decimal> JanJ0 { get; set; }
        public Nullable<decimal> JanJ1 { get; set; }
        public Nullable<decimal> JanJ2 { get; set; }
        public Nullable<decimal> JanJ3 { get; set; }
        public Nullable<decimal> Feb0 { get; set; }
        public Nullable<decimal> Feb1 { get; set; }
        public Nullable<decimal> Feb2 { get; set; }
        public Nullable<decimal> Feb3 { get; set; }
        public Nullable<decimal> FebJ0 { get; set; }
        public Nullable<decimal> FebJ1 { get; set; }
        public Nullable<decimal> FebJ2 { get; set; }
        public Nullable<decimal> FebJ3 { get; set; }
        public Nullable<decimal> Mar0 { get; set; }
        public Nullable<decimal> Mar1 { get; set; }
        public Nullable<decimal> Mar2 { get; set; }
        public Nullable<decimal> Mar3 { get; set; }
        public Nullable<decimal> MarJ0 { get; set; }
        public Nullable<decimal> MarJ1 { get; set; }
        public Nullable<decimal> MarJ2 { get; set; }
        public Nullable<decimal> MarJ3 { get; set; }
        public Nullable<decimal> Apr0 { get; set; }
        public Nullable<decimal> Apr1 { get; set; }
        public Nullable<decimal> Apr2 { get; set; }
        public Nullable<decimal> Apr3 { get; set; }
        public Nullable<decimal> AprJ0 { get; set; }
        public Nullable<decimal> AprJ1 { get; set; }
        public Nullable<decimal> AprJ2 { get; set; }
        public Nullable<decimal> AprJ3 { get; set; }
        public Nullable<decimal> May0 { get; set; }
        public Nullable<decimal> May1 { get; set; }
        public Nullable<decimal> May2 { get; set; }
        public Nullable<decimal> May3 { get; set; }
        public Nullable<decimal> MayJ0 { get; set; }
        public Nullable<decimal> MayJ1 { get; set; }
        public Nullable<decimal> MayJ2 { get; set; }
        public Nullable<decimal> MayJ3 { get; set; }
        public Nullable<decimal> Jun0 { get; set; }
        public Nullable<decimal> Jun1 { get; set; }
        public Nullable<decimal> Jun2 { get; set; }
        public Nullable<decimal> Jun3 { get; set; }
        public Nullable<decimal> JunJ0 { get; set; }
        public Nullable<decimal> JunJ1 { get; set; }
        public Nullable<decimal> JunJ2 { get; set; }
        public Nullable<decimal> JunJ3 { get; set; }
        public Nullable<decimal> Jul0 { get; set; }
        public Nullable<decimal> Jul1 { get; set; }
        public Nullable<decimal> Jul2 { get; set; }
        public Nullable<decimal> Jul3 { get; set; }
        public Nullable<decimal> JulJ0 { get; set; }
        public Nullable<decimal> JulJ1 { get; set; }
        public Nullable<decimal> JulJ2 { get; set; }
        public Nullable<decimal> JulJ3 { get; set; }
        public Nullable<decimal> Aug0 { get; set; }
        public Nullable<decimal> Aug1 { get; set; }
        public Nullable<decimal> Aug2 { get; set; }
        public Nullable<decimal> Aug3 { get; set; }
        public Nullable<decimal> AugJ0 { get; set; }
        public Nullable<decimal> AugJ1 { get; set; }
        public Nullable<decimal> AugJ2 { get; set; }
        public Nullable<decimal> AugJ3 { get; set; }
        public Nullable<decimal> Sep0 { get; set; }
        public Nullable<decimal> Sep1 { get; set; }
        public Nullable<decimal> Sep2 { get; set; }
        public Nullable<decimal> Sep3 { get; set; }
        public Nullable<decimal> SepJ0 { get; set; }
        public Nullable<decimal> SepJ1 { get; set; }
        public Nullable<decimal> SepJ2 { get; set; }
        public Nullable<decimal> SepJ3 { get; set; }
        public Nullable<decimal> Oct0 { get; set; }
        public Nullable<decimal> Oct1 { get; set; }
        public Nullable<decimal> Oct2 { get; set; }
        public Nullable<decimal> Oct3 { get; set; }
        public Nullable<decimal> OctJ0 { get; set; }
        public Nullable<decimal> OctJ1 { get; set; }
        public Nullable<decimal> OctJ2 { get; set; }
        public Nullable<decimal> OctJ3 { get; set; }
        public Nullable<decimal> Nov0 { get; set; }
        public Nullable<decimal> Nov1 { get; set; }
        public Nullable<decimal> Nov2 { get; set; }
        public Nullable<decimal> Nov3 { get; set; }
        public Nullable<decimal> NovJ0 { get; set; }
        public Nullable<decimal> NovJ1 { get; set; }
        public Nullable<decimal> NovJ2 { get; set; }
        public Nullable<decimal> NovJ3 { get; set; }
        public Nullable<decimal> Dec0 { get; set; }
        public Nullable<decimal> Dec1 { get; set; }
        public Nullable<decimal> Dec2 { get; set; }
        public Nullable<decimal> Dec3 { get; set; }
        public Nullable<decimal> DecJ0 { get; set; }
        public Nullable<decimal> DecJ1 { get; set; }
        public Nullable<decimal> DecJ2 { get; set; }
        public Nullable<decimal> DecJ3 { get; set; }
    }
}
