//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkType
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> MonthlyTarget { get; set; }
    }
}
