//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationStat
    {
        public string Id { get; set; }
        public string Date { get; set; }
        public Nullable<long> Errors { get; set; }
        public Nullable<long> SentSms { get; set; }
        public Nullable<long> SentMail { get; set; }
        public Nullable<long> ServiceId { get; set; }
    }
}
