//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public long ID { get; set; }
        public string Reciept { get; set; }
        public string item { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> priceinc { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Description { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string SubCategory { get; set; }
        public string Category { get; set; }
        public string Company { get; set; }
    }
}
