//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public long ID { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public string trantype { get; set; }
        public string ProviderAccount { get; set; }
        public string AccountName { get; set; }
        public string ReturnUrl { get; set; }
        public string SendingUrl { get; set; }
    }
}
