//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Source { get; set; }
        public string Location { get; set; }
        public string SourceRefrence { get; set; }
        public string SourceMobileNumber { get; set; }
        public string Description { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Status { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string ReceiptNo { get; set; }
        public string Polls { get; set; }
    }
}
