//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickinCheck
    {
        public long Id { get; set; }
        public string Reciept { get; set; }
        public Nullable<int> Lines { get; set; }
        public Nullable<int> Picled { get; set; }
    }
}
