//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosMenu
    {
        public long ID { get; set; }
        public string button { get; set; }
        public string caption { get; set; }
        public string code { get; set; }
        public string color { get; set; }
        public string company { get; set; }
        public string tax { get; set; }
    }
}
