//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long Id { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<long> EquipmentId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string RaiseBy { get; set; }
        public string ProjectTeam { get; set; }
        public string ProgressReport { get; set; }
        public string RaiserEmail { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Priority { get; set; }
        public string ItemType { get; set; }
    }
}
