//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetailKingEntities : DbContext
    {
        public RetailKingEntities()
            : base("name=RetailKingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessOption> AccessOptions { get; set; }
        public DbSet<AccountCredenitial> AccountCredenitials { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Activeco> Activecoes { get; set; }
        public DbSet<AdPosition> AdPositions { get; set; }
        public DbSet<AdSpace> AdSpaces { get; set; }
        public DbSet<Advert> Adverts { get; set; }
        public DbSet<AgentUser> AgentUsers { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<CashCollection> CashCollections { get; set; }
        public DbSet<CashoutType> CashoutTypes { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CollectionPoint> CollectionPoints { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<CreditNote> CreditNotes { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CustomerCode> CustomerCodes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DailyCashierSale> DailyCashierSales { get; set; }
        public DbSet<DailySale> DailySales { get; set; }
        public DbSet<DailyStat> DailyStats { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<DomainUser> DomainUsers { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<FacilityType> FacilityTypes { get; set; }
        public DbSet<Faq> Faqs { get; set; }
        public DbSet<FaqType> FaqTypes { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<FeatureType> FeatureTypes { get; set; }
        public DbSet<Guest> Guests { get; set; }
        public DbSet<Infographic> Infographics { get; set; }
        public DbSet<InfographicType> InfographicTypes { get; set; }
        public DbSet<Invite> Invites { get; set; }
        public DbSet<InvoiceLine> InvoiceLines { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<ItemImage> ItemImages { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemVariation> ItemVariations { get; set; }
        public DbSet<JobCategory> JobCategories { get; set; }
        public DbSet<JobSubCategory> JobSubCategories { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<Loss> Losses { get; set; }
        public DbSet<LossLine> LossLines { get; set; }
        public DbSet<LoyaltyScheme> LoyaltySchemes { get; set; }
        public DbSet<MailGroup> MailGroups { get; set; }
        public DbSet<MailingService> MailingServices { get; set; }
        public DbSet<MailList> MailLists { get; set; }
        public DbSet<MailSetting> MailSettings { get; set; }
        public DbSet<MailTemplate> MailTemplates { get; set; }
        public DbSet<MenuItem> MenuItems { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MonthlySale> MonthlySales { get; set; }
        public DbSet<MonthlyStat> MonthlyStats { get; set; }
        public DbSet<NetworkSale> NetworkSales { get; set; }
        public DbSet<NetworkType> NetworkTypes { get; set; }
        public DbSet<NotificationStat> NotificationStats { get; set; }
        public DbSet<OrderLine> OrderLines { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Partner> Partners { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<PickinCheck> PickinChecks { get; set; }
        public DbSet<PosKey> PosKeys { get; set; }
        public DbSet<PosMenu> PosMenus { get; set; }
        public DbSet<PosPrinter> PosPrinters { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProxySetting> ProxySettings { get; set; }
        public DbSet<PurchaseLine> PurchaseLines { get; set; }
        public DbSet<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<QuotationLine> QuotationLines { get; set; }
        public DbSet<Quotation> Quotations { get; set; }
        public DbSet<RatingZone> RatingZones { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<RegCode> RegCodes { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RegistrationCode> RegistrationCodes { get; set; }
        public DbSet<ReturnLine> ReturnLines { get; set; }
        public DbSet<Return> Returns { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<Sales_Lines> Sales_Lines { get; set; }
        public DbSet<SalesLineSammary> SalesLineSammaries { get; set; }
        public DbSet<seat> seats { get; set; }
        public DbSet<ServiceActionType> ServiceActionTypes { get; set; }
        public DbSet<shift> shifts { get; set; }
        public DbSet<shopingList> shopingLists { get; set; }
        public DbSet<SM> SMS { get; set; }
        public DbSet<StartPage> StartPages { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Storekey> Storekeys { get; set; }
        public DbSet<SubMenuItem> SubMenuItems { get; set; }
        public DbSet<Suburb> Suburbs { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Syskey> Syskeys { get; set; }
        public DbSet<temp> temps { get; set; }
        public DbSet<Tranname> Trannames { get; set; }
        public DbSet<TransactionData> TransactionDatas { get; set; }
        public DbSet<Transfer> Transfers { get; set; }
        public DbSet<Trantype> Trantypes { get; set; }
        public DbSet<Valuation> Valuations { get; set; }
        public DbSet<VariationType> VariationTypes { get; set; }
        public DbSet<YomoneyService> YomoneyServices { get; set; }
        public DbSet<Denomination> Denominations { get; set; }
        public DbSet<MenuAccess> MenuAccesses { get; set; }
        public DbSet<ProjectType> ProjectTypes { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
        public DbSet<TransferingLine> TransferingLines { get; set; }
    }
}
