//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Access { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public string InstitutionId { get; set; }
    }
}
