//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLineSammary
    {
        public long Id { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> DeliveredQty { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Received { get; set; }
        public Nullable<decimal> Varience { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<bool> SuppierPicking { get; set; }
        public Nullable<bool> DeliveryPicking { get; set; }
        public Nullable<decimal> GPAmount { get; set; }
    }
}
