//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceActionType
    {
        public long Id { get; set; }
        public string ServiceType { get; set; }
        public string ActionName { get; set; }
        public string Description { get; set; }
        public Nullable<long> TranTypeId { get; set; }
        public Nullable<long> YomoneyId { get; set; }
    }
}
