//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public long ID { get; set; }
        public string AccountCode { get; set; }
        public string SupplierName { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<long> Period { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Company { get; set; }
        public string ServiceType { get; set; }
        public string ParentAccount { get; set; }
        public string Email { get; set; }
        public string ParentId { get; set; }
        public string Branch { get; set; }
    }
}
