//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Trade { get; set; }
        public string Business { get; set; }
        public string lease { get; set; }
        public Nullable<System.DateTime> ExpireryDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> Effected { get; set; }
        public string terms { get; set; }
        public Nullable<long> EntityId { get; set; }
    }
}
