//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionData
    {
        public long ID { get; set; }
        public string TransactionName { get; set; }
        public string Type { get; set; }
        public string Debit1 { get; set; }
        public string Debit2 { get; set; }
        public string Debit3 { get; set; }
        public string Debit4 { get; set; }
        public string Debit5 { get; set; }
        public string Debit6 { get; set; }
        public string Credit1 { get; set; }
        public string Credit2 { get; set; }
        public string Credit3 { get; set; }
        public string Credit4 { get; set; }
        public string Credit5 { get; set; }
        public string Credit6 { get; set; }
    }
}
