//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valuation
    {
        public long Id { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> TicketId { get; set; }
        public Nullable<decimal> LandValuation { get; set; }
        public Nullable<decimal> Improvement { get; set; }
        public string Details { get; set; }
        public string AssetName { get; set; }
        public Nullable<decimal> LandArea { get; set; }
        public Nullable<decimal> ImprovementArea { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Evauluator { get; set; }
        public Nullable<long> EvauluatorId { get; set; }
    }
}
